name:                hanspell
version:             0.2.6.0
github:              "9beach/hanspell-hs"
license:             MIT
author:              "Hyunrae Cho"
maintainer:          "9beach@gmail.com"
copyright:           "2020 Hyunrae Cho"
category:            "language,korean,spellchecker"

extra-source-files:
- README.md
- hanspell-screenshot.png
- test/long-paragraph-sample.txt

synopsis:            Korean spell checker
description:
    This package includes @hanspell@, a simple command line spell check 
    program and a library, @Language.Hanspell@. Both of them are based on 
    DAUM spell check web service and Pusan National University spell check 
    web service.

dependencies:
- base                  >= 4.7 && < 5
- aeson                 >= 1.4.7 && < 1.6
- bytestring            >= 0.10.8 && < 0.12
- text                  >= 1.2.3 && < 1.3
- transformers          >= 0.5.2 && < 0.7
- unix                  >= 2.7.2 && < 2.8
- directory             >= 1.3.0 && < 1.4
- async                 >= 2.2.2 && < 2.3
- html-entities         >= 1.1.4 && < 1.2
- http-client           >= 0.6.4 && < 0.8
- http-types            >= 0.12.3 && < 0.13
- http-client-tls       >= 0.3.5 && < 0.4
- regex-compat-tdfa     >= 0.95.1 && < 0.96
- split                 >= 0.2.3 && < 0.3
- utf8-string           >= 1.0.1 && < 1.1

library:
  source-dirs:           src

executables:
  hanspell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanspell

tests:
  hanspell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanspell
    - hspec
    - QuickCheck
