name:                hanspell
version:             0.2.0.0
github:              "9beach/hanspell-hs"
license:             MIT
author:              "Hyunrae Cho"
maintainer:          "9beach@gmail.com"
copyright:           "2020 Hyunrae Cho"
category:            "language,korean,spellchecker"

extra-source-files:
- README.md
- test/long-paragraph-sample.txt

synopsis:            Korean spell checker
description:
    This package includes @hanspell@, a simple command line spell check 
    program and a library, @Language.Hanspell@. Both of them are based on 
    DAUM spell check web service and Pusan National University spell check 
    web service.

dependencies:
- base >= 4.7 && < 5
- async
- transformers
- aeson
- http-client
- http-client-tls
- http-types
- bytestring
- utf8-string
- html-entities
- regex-compat-tdfa
- directory
- text
- unix
- split

library:
  source-dirs:           src

executables:
  hanspell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanspell

tests:
  hanspell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanspell
    - hspec
    - QuickCheck
